---
- name: installing nginx and enabling
  hosts: webserver
  remote_user: root
  become: yes
  vars:
   pack_name: nginx
  tasks:
   - name: updating
     apt:
      update_cache: yes
   - name: install nginx
     apt:
      name: "{{pack_name}}"
      state: present
   - name: systemctl
     service:
      name: "{{pack_name}}"
      state: started
      enabled: yes
